First run through
TypoConsult/extension pull request #32
Opened 2024-01-26 13:57 UTC by clausharup

2024-01-27 06:35 UTC, rlvk-tc requested changes

2024-01-27 06:35 UTC, rlvk-tc commented on templates/extension/12/composer.json
> +        "typo3/cms-backend": "^12.4",
Jeg kan ikke lige se at backend og fluid er nødvendige? Ser ikke ud til at blive brugt

2024-01-27 06:35 UTC, rlvk-tc commented on templates/extension/12/Configuration/Extbase/Persistence/Classes.php
> +            'xxxxxXxxxxxxx' => [
Synes ikke dette er en forbedring

2024-01-27 06:35 UTC, rlvk-tc commented on templates/extension/12/ext_localconf.php
> +    $labelPrefix = LabelUtility::getPath(identifier: 'db', extKey: $extKey);
Fedt, men forstår ikke hvorfor $extKey angives. Den finder selv ud af det

2024-01-27 06:35 UTC, rlvk-tc commented on templates/extension/12/Configuration/Icons.php
> +return (new IconLoaderService(GeneralConstants::EXT_KEY))->readIconsFromFolder()->getIconsForIconsFile();
Bliver mere og mere fan af at denne slags er i flere linjer, så man bedre kan forstå hvad der egentlig sker

2024-01-27 06:35 UTC, rlvk-tc commented on templates/extension/12/Classes/Controller/PluginController.php
> +        $content = $this->contentRepository->findByUid($uid);
Smukt!

2024-01-27 06:35 UTC, rlvk-tc commented on templates/extension/12/Configuration/TCA/Overrides/tt_content.php
> +$labelPrefix = LabelUtility::getPath(identifier: 'db', extKey: GeneralConstants::EXT_KEY) . $table;
Jeg forstår ikke hvorfor extKey angives her? Den finder jo selv ud af det

2024-01-27 06:35 UTC, rlvk-tc commented on templates/extension/12/Classes/Hooks/VoilaHook.php
> +        $element = GeneralUtility::makeInstance(ContentRepository::class)->findByUidRaw($params['element']->getUid());
Igen foretrækker jeg flere linjer, så man nemmere kan læse koden

2024-01-29 08:40 UTC, clausharup commented on templates/extension/12/composer.json
> +        "typo3/cms-backend": "^12.4",
Fixed

2024-01-29 08:41 UTC, clausharup commented on templates/extension/12/ext_localconf.php
> +    $labelPrefix = LabelUtility::getPath(identifier: 'db', extKey: $extKey);
Fixed - det er fordi den SKAL med i CLI mode, så jeg har den bare ALTID med

2024-01-29 08:41 UTC, clausharup commented on templates/extension/12/Configuration/TCA/Overrides/tt_content.php
> +$labelPrefix = LabelUtility::getPath(identifier: 'db', extKey: GeneralConstants::EXT_KEY) . $table;
See above

2024-01-29 09:36 UTC, rlvk-tc approved these changes

2024-01-29 09:37 UTC, merged